const samplePatients = [
    {
        id: 1,
        firstName: "Pat",
        lastName: "Smith",
        nickName: "Pat",
        age: 25,
        engagementRate: 0.8,
        gender: "male",
        email: "pat@diabetemail.com",
    },

    {
        id: 2,
        firstName: "Tit",
        lastName: "Eri",
        nickName: "Gala",
        age: 60,
        engagementRate: 0.9,
        gender: "female",
        email: "Tit@diabetemail.com",
    },
    {
        id: 3,
        firstName: "Justin",
        lastName: "Chen",
        nickName: "Hu",
        age: 20,
        engagementRate: 0.3,
        gender: "female",
        email: "TChen@diabetemail.com",
    },
    {
        id: 4,
        firstName: "Steven",
        lastName: "Curry",
        nickName: "three",
        age: 33,
        engagementRate: 0.7,
        gender: "male",
        email: "Curry@diabetemail.com",
    },
    {
        id: 5,
        firstName: "James",
        lastName: "Alista",
        nickName: "KOO",
        age: 10,
        engagementRate: 0.4,
        gender: "male",
        email: "Alista@diabetemail.com",
    },
    {
        id: 6,
        firstName: "Emma",
        lastName: "Alice",
        nickName: "bili",
        age: 24,
        engagementRate: 0.3,
        gender: "female",
        email: "Alice@diabetemail.com",
    },
    {
        id: 7,
        firstName: "Tony",
        lastName: "Star",
        nickName: "skyyy",
        age: 20,
        engagementRate: 0.7,
        gender: "male",
        email: "skyyy@diabetemail.com",
    },
    {
        id: 8,
        firstName: "Saito",
        lastName: "ichiban",
        nickName: "ramen",
        age: 81,
        engagementRate: 0.2,
        gender: "female",
        email: "ichiban@diabetemail.com",
    },
    {
        id: 9,
        firstName: "Hurry",
        lastName: "Angelica",
        nickName: "tada",
        age: 91,
        engagementRate: 0.3,
        gender: "female",
        email: "Angelica@diabetemail.com",
    },
    {
        id: 10,
        firstName: "Ben",
        lastName: "Jason",
        nickName: "backworld",
        age: 49,
        engagementRate: 0.1,
        gender: "male",
        email: "Jason@diabetemail.com",
    },
];
module.exports = samplePatients;
